### ISSUE TITLE
error while running the step 2 of PLMSearch pipeline

### ISSUE THREAD

**Issue by daisykuma22** [maovshao/PLMSearch#10]
Hello!
Thank you for the excellent work on PLMSearch!
I'm currently testing PLMSearch using a small amount of protein sequences. This file contains approximately 4592 sequences.
Commands used: 
`python ./plmsearch/embedding_generate.py -f ../plmsearch/Am_MAG5.fasta -e ../plmsearch/Am_embedding.pkl --nogpu`

`python ./plmsearch/ptam_generate.py -f ../plmsearch/AM_MAG5.fastA -o ../plmsearch/ofam_result.json`

`python plmsearch/main_pfam.py -qpr ../plmsearcn/pfam_result.json -tpr ./plmsearch_data/swissprot/pfam_result.json -c`

`python plmsearch/main_similarity.py -iqe ../plmsearch/Am_embedding.pkl -ite plmsearch_data/swissprot/embedding.pkl -smp plmsearch_data/model/plmsearch.sav -isr ../plmsearch/search result/pfamclan -d`

However, something went wrong in the last step. See the following screenshot:
![1733885463998](https://github.com/user-attachments/assets/170f03ac-6fbd-461e-a03e-a23276ec9e39)
Is it a problem with the sequence? I've checked this sequence and didn't find any problems.
>Am_MAG5_SD8528_NODE_337_length_15874_cov_0.812536_1 # 3 # 278 # -1 # ID=1_1;partial=10;start_type=ATG;rbs_motif=None;rbs_spacer=None;gc_cont=0.446
MAIISSKQTPSEPNKPSSQRQPKKVSERDNLLQPQADVNESKPEESIRPSQFADYIGQKD
LKDVLEIAIQAAKSRGEVLDHLLLYGPPGLGK
 Is there a limit on the length of the sequence? Could you help me figure it out? Thanks a lot.

**Comment by maovshao** [comment]
[Bug reproduce.pdf](https://github.com/user-attachments/files/18102423/Bug.reproduce.pdf)

Hello, thank you for your feedback.

I have reproduced the bug locally and found the problem. For details, please refer to the document I uploaded `Bug reproduce.pdf`

Summary: The cause of the bug is that **your Protein ID contains spaces**. Due to the third-party software `Pfamscan`, the original ProteinID **should not** contain spaces.

Hope this response is helpful.

**Comment by daisykuma22** [comment]
@maovshao Thanks for your reply. The problem has been solved. The results have three columns, i.e. query ID, Uniprot ID, and similarity value. But we still don't know the specific names and functions of the proteins. I find that the results generated by the online tool at https://dmiip.sjtu.edu.cn/PLMSearch/ contain detailed information.

**Comment by maovshao** [comment]
With the Uniprot ID, you can search it in Uniprot (https://www.uniprot.org/). 

The information of PLMSearch Webserver (https://dmiip.sjtu.edu.cn/PLMSearch/) is also got from Uniprot.
