### ISSUE TITLE
How can I get a3m format files based on "sequence_alignment.txt" file?

### ISSUE THREAD

**Issue by Zimiao1025** [maovshao/PLMSearch#3]
Since a3m format file like the outputs of BLAST and DeepMSA2 can directly input to AlphaFold2, how can I get a3m format files based on the outputs of similarity calculation and how to set thresholds of similarity scores to ensure accuracy and recall of msa.

**Comment by maovshao** [comment]
For the first question, a3m files are actually the result of a Multiple Sequence Alignment (MSA). PLMSearch can provide the similarity between query-target pairs, and PLMAlign can provide pairwise sequence alignment (PSA) on this basis. The MSA is the follow-up work.

Regarding thresholds, we discussed them in detail in the paper ([DOI](https://doi.org/10.1038/s41467-024-46808-5)). Generally speaking, protein pairs with a similarity lower than **0.3** are usually assumed as randomly selected irrelevant protein pairs.

For more information about similarity, you can refer to "Fig. 6: Reference similarity" in the paper. In addition, The posterior probability corresponding to the similarity is shown in Supplementary Table 12. See "Reference similarity" Supplement Section for more details.

Hope this information is helpful to you.

Best.
