### ISSUE TITLE
Issue with Data Download

### ISSUE THREAD

**Issue by Javi-Rop** [maovshao/PLMSearch#4]
Hi there,

First of all, I'd like to extend my heartfelt congratulations on the work done in the repository. I'm thrilled to try out PLMSearch and harness its capabilities. However, I've encountered a small hiccup while attempting to download the data from the plmsearch_data folder. It seems that the page where the data is hosted is either offline or inaccessible at the moment. Is there an alternative way to access the data or any workaround I could try?

Thank you for your attention and for providing this amazing tool!

Best regards, Javier

**Comment by maovshao** [comment]
Hello, just now, I tried two ways to download plmsearch_data:
1. Click the link to download directly in the browser (Chrome)
2. Use the command wget https://dmiip.sjtu.edu.cn/PLMSearch/static/download/plmsearch_data.tar.gz to download
Currently, both methods can be used to download normally.

In fact, the data of plmsearch_data is hosted on PLMSearch's server (https://dmiip.sjtu.edu.cn/PLMSearch). If you can access the server normally, you should be able to download data normally. It is worth noting that the data size of plmsearch_data is approximately 12G, which may require you to maintain a stable network connection.

Please try a few more times and if you still have problems, I'll think of other ways to solve it.

Best,

Wei Liu
