### ISSUE TITLE
plmsearch installation

### ISSUE THREAD

**Issue by npcooley** [maovshao/PLMSearch#7]
Hi,

I'm trying to install plmsearch locally, and am not having any luck. Do you have a working docker container or dockerfile I could see or use?

**Comment by maovshao** [comment]
Sure. As we described in our paper, we cooperated with Code Ocean. The results of PLMSearch can also be reproduced through the capsule published on Code Ocean ([https://doi.org/10.24433/CO.8325548.v1](https://doi.org/10.24433/CO.8325548.v1)).

Hope you enjoy it.

Best.
