### ISSUE TITLE
About the dataset of protein used individually replaced

### ISSUE THREAD

**Issue by ShiboSusu** [maovshao/PLMSearch#8]
The data path I need to replace for the protein data that needs to be compared is 
./plmsearch/plmsearch_data/scope_test/protein.fasta?
In fact I only want to compare my dataset with  Swissprot.And output the similarity...

**Comment by maovshao** [comment]
[pipeline.ipynb](https://github.com/maovshao/PLMSearch/blob/main/pipeline.ipynb) fully shows how to "compare the dataset with Swiss-Prot".

Tell me more if you have further questions.

Best.

**Comment by ShiboSusu** [comment]
Teacher Liu, I found that the intermediate files produced by the code run are not deleted. The result is that if I run with my own protein data, if there is a problem somewhere in the middle, it will continue to run with the previously produced intermediate files without reporting an error.

**Comment by maovshao** [comment]
Sure. You should make sure that the middle result for each step is correct to ensure your expected final result.

We offer our code and result for your reference. You shall feel free to adjust the pipeline as you need, since it seems that you want to delete the middle result, for example.

Best.
